name: Bump version

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create a GitHub release
        uses: danilohorta/test-release-workflow/.github/workflows/release-workflow.yml@main
