name: Bla

on: workflow_dispatch

jobs:
  create-release:
    name: Create a release
    uses: danilohorta/test-release-workflow/.github/workflows/release-create.yml@main

permissions:
  contents: write
